name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
    inputs:
      fuzz_seconds:
        description: 'Fuzzing duration in seconds'
        required: false
        default: '3600'

permissions: read-all

jobs:
  batch:
    uses: ./.github/workflows/clusterfuzzlite-shared.yml
    with:
      job_name: Batch fuzzing
      run_mode: batch
      # Allow longer batch runs to expand coverage between pushes.
      fuzz_seconds: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.fuzz_seconds != '' && fromJSON(github.event.inputs.fuzz_seconds) || 3600 }}
      output_sarif: true
