name: ClusterFuzzLite shared job

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        default: ClusterFuzzLite
      sanitizers_json:
        type: string
        default: '{"sanitizer":["address","undefined","memory"]}'
      run_fuzzers:
        type: boolean
        default: true
      run_mode:
        type: string
        default: code-change
      fuzz_seconds:
        type: number
        default: 60
      output_sarif:
        type: boolean
        default: false
      upload_build:
        type: boolean
        default: false
      run_base_install:
        type: boolean
        default: true

permissions: read-all

jobs:
  fuzz:
    name: ${{ inputs.job_name }} (${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.sanitizers_json) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare ccache directory
        run: mkdir -p .cfl-ccache

      - name: Restore ccache (${{ matrix.sanitizer }})
        id: cfl-ccache-cache
        uses: actions/cache/restore@v4
        with:
          path: .cfl-ccache
          key: ${{ format('cfl-ccache-{0}-{1}-{2}-{3}', runner.os, matrix.sanitizer, hashFiles('ci/test/run-cfl-helper.sh', 'ci/test/cfl-common.sh'), github.run_id) }}
          restore-keys: |
            ${{ format('cfl-ccache-{0}-{1}-{2}-', runner.os, matrix.sanitizer, hashFiles('ci/test/run-cfl-helper.sh', 'ci/test/cfl-common.sh')) }}
            ${{ format('cfl-ccache-{0}-{1}-', runner.os, matrix.sanitizer) }}

      - name: Restore depends cache (${{ matrix.sanitizer }})
        id: depends-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/depends/x86_64-pc-linux-gnu
          key: ${{ format('cfl-depends-{0}-{1}-{2}', runner.os, matrix.sanitizer, hashFiles('.clusterfuzzlite/build.sh', 'depends/packages.md', 'depends/funcs.mk', 'depends/patches/**', 'depends/packages/**')) }}
          restore-keys: |
            ${{ format('cfl-depends-{0}-{1}-', runner.os, matrix.sanitizer) }}

      - name: ClusterFuzzLite base install (${{ matrix.sanitizer }})
        if: ${{ inputs.run_base_install }}
        run: ./ci/test/run-cfl-helper.sh base-install "${{ matrix.sanitizer }}"
        shell: bash
        env:
          CCACHE_MAXSIZE: 500M

      - name: Build fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          sanitizer: ${{ matrix.sanitizer }}
          upload-build: ${{ inputs.upload_build }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Sjors/sv2-tp-fuzz-storage.git
          storage-repo-branch: master
          storage-repo-branch-coverage: gh-pages
        env:
          CCACHE_DIR: /workspace/.cfl-ccache
          CCACHE_MAXSIZE: 500M

      - name: Save ccache (${{ matrix.sanitizer }})
        if: ${{ github.event_name != 'push' && steps.cfl-ccache-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: .cfl-ccache
          key: ${{ format('cfl-ccache-{0}-{1}-{2}-{3}', runner.os, matrix.sanitizer, hashFiles('ci/test/run-cfl-helper.sh', 'ci/test/cfl-common.sh'), github.run_id) }}

      - name: Check depends directory (${{ matrix.sanitizer }})
        id: depends_dir
        shell: bash
        run: |
          if [ -d "${{ github.workspace }}/depends/x86_64-pc-linux-gnu" ]; then
            echo "exists=true" >>"$GITHUB_OUTPUT"
          else
            echo "exists=false" >>"$GITHUB_OUTPUT"
          fi

      - name: Save depends cache (${{ matrix.sanitizer }})
        if: ${{ github.event_name != 'push' && steps.depends-cache.outputs.cache-hit != 'true' && steps.depends_dir.outputs.exists == 'true' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/depends/x86_64-pc-linux-gnu
          key: ${{ steps.depends-cache.outputs.cache-primary-key }}

      - name: Run fuzzers (${{ matrix.sanitizer }})
        if: ${{ inputs.run_fuzzers }}
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Sjors/sv2-tp-fuzz-storage.git
          storage-repo-branch: master
          storage-repo-branch-coverage: gh-pages
          fuzz-seconds: ${{ inputs.fuzz_seconds }}
          mode: ${{ inputs.run_mode }}
          output-sarif: ${{ inputs.output_sarif }}
        env:
          CCACHE_DIR: /workspace/.cfl-ccache
          CCACHE_MAXSIZE: 500M
